### PR TITLE
Adds documentation

### LINKED ISSUE #66: Add documentation

### PR DESCRIPTION
**Pull request by joelalejandro**
A rendered version of this markdown file can be seen here:
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation

Sections:

- [x] Repo description
- [x] Feature (brief description)
  - [x] Operation-driven API
  - [x] Declarative style for resource definition
  - [x] CRUD database operations
  - [x] Transport layer integrations
  - [x] Relationships and sideloading
  - [x] Error handling
  - [x] User/Role presence authorization
  - [x] Extensibility
- [x] Getting started
- [x] Resources
  - [x] What is a resource?
  - [x] Declaration syntax
  - [x] Accepted types
- [x] Operations
  - [x] What is an operation?
  - [x] Operation types
    - [x] get
    - [x] add
    - [x] update
    - [x] remove
- [x] Transport layers
  - [x] jsonApiKoa
    - [x] Usage
    - [x] Converting operations into HTTP endpoints
    - [x] URL mapping
- [x] Processors
  - [x] What is a processor?
  - [x] The `OperationProcessor` class
  - [x] How does an operation gets executed?
  - [x] Controlling errors while executing an operation
  - [x] Extending the OperationProcessor
  - [x] The `KnexProcessor` class
  - [x] Extending the KnexProcessor
- [x] Authorization
  - [x] Defining a User resource
  - [x] Implementing a User processor
  - [x] Using the `@Authorize` decorator
  - [x] Using the `IfUser()` conditional helper
  - [x] Front-end requirements
- [x] The JSONAPI Application
  - [x] What is a JSONAPI Application?
  - [x] Referencing types and processors
  - [x] Using a default processor

Resolves #66.

### CODE REVIEW

**Comment by spersico** [comment]
In both examples of the custom OperationProcessor there's a type error:
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#how-does-an-operation-gets-executed
image

and in the Controlling Errors example:
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#controlling-errors-while-executing-an-operation
image

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#extending-the-operationprocessor-class
image

**Comment by spersico** [comment]
Also:
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#extending-the-operationprocessor-class
image

and

image

**Comment by spersico** [comment]
Finnally in the last example:
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#extending-the-knexprocessor-class

image

The property _relationships_ is missing.

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#defining-an-user-resource
image

**Comment by spersico** [comment]
In the user creation example, the user class doesn't seems to have the needed attributes
image

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#controlling-errors-while-executing-an-operation
There's a _fs.readFileSync(file)_
_fs_ is undefined, and you are already importing it above.

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#implementing-a-session-processor
image
Neither _hash_ nor _Log_ are being used in the example, we could remove those.

image
Missing prop _relationships_

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#implementing-a-session-processor
We could add anoter notice letting the user know that under no circumstances storing the password in the db as plain text is a good idea, and that this is just an example.

**Comment by spersico** [comment]
https://github.com/ebryn/jsonapi-ts/tree/joel/documentation#using-the-authorize-decorator
As far as I can see in the jsonapi-ts code, the current implementation of the Authorize decorator is applicable only to _"get", "add", "update", "remove"_ operations. 
We should let the user know that, I think.

**Comment by joelalejandro** [comment]
Comments will be taken care of in future PRs.

**Pull request merged**
